/* Generated By:JavaCC: Do not edit this line. CircuitParserConstants.java */
package GCParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CircuitParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COLON = 4;
  /** RegularExpression Id. */
  int PERIOD = 5;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int LINE_ENDING = 7;
  /** RegularExpression Id. */
  int OPEN_PAREN = 8;
  /** RegularExpression Id. */
  int CLOSE_PAREN = 9;
  /** RegularExpression Id. */
  int INPUT_MARK = 10;
  /** RegularExpression Id. */
  int OUTPUT_MARK = 11;
  /** RegularExpression Id. */
  int SIGNED_MARK = 12;
  /** RegularExpression Id. */
  int INCLUDE = 13;
  /** RegularExpression Id. */
  int VERSION = 14;
  /** RegularExpression Id. */
  int UNSIGNED_MARK = 15;
  /** RegularExpression Id. */
  int START_PARTY = 16;
  /** RegularExpression Id. */
  int END_PARTY = 17;
  /** RegularExpression Id. */
  int PATH = 18;
  /** RegularExpression Id. */
  int IDENTIFIER = 19;
  /** RegularExpression Id. */
  int INTEGER = 20;
  /** RegularExpression Id. */
  int COMMENT = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\":\"",
    "\".\"",
    "\",\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\".input\"",
    "\".output\"",
    "\"signed\"",
    "\".include\"",
    "\".version\"",
    "\"unsigned\"",
    "\".startparty\"",
    "\".endparty\"",
    "<PATH>",
    "<IDENTIFIER>",
    "<INTEGER>",
    "<COMMENT>",
  };

}
